project:
  type: website
  render:
    - "**/*.qmd"
    - "!**/resources/*.qmd"
  resources:
    - files/
    - images/
    - projects/banners/
    - blog/banners/
  output-dir: _site

website:
  title: "Kader Mohideen"
  image: images/card.png
  favicon: images/favicon.png
  description: "Cybersecurity solution architect. Notes on security, AI/ML, and emerging defensive tech."
  site-url: https://kader-xai.github.io
  repo-url: https://github.com/kader-xai/kader-xai.github.io
  back-to-top-navigation: false
  twitter-card: true
  open-graph:
    locale: en_US
    image: images/card.png
  page-footer:
    center: "© <span id='footer-year'></span> [Kader Mohideen](https://kader-xai.github.io)"
    border: true
    background: light
  search:
    location: navbar
    type: overlay
    copy-button: true
  navbar:
    left:
      - icon: person-badge
        href: about.qmd
        text: About
      - icon: file-text
        href: blog.qmd
        text: Blog
      - icon: file-bar-graph
        href: projects.qmd
        text: Projects
      - icon: file-pdf
        href: files/Kader_Mohideen_CV.pdf
        text: CV
    right:
      - text: "<i class='fa-brands fa-linkedin'></i>"
        href: https://www.linkedin.com/in/kader-m-1a6023a6/
        target: _blank
      - text: "<i class='fa-brands fa-github'></i>"
        href: https://github.com/kader-xai
        target: _blank

format:
  html:
    toc: true
    toc-depth: 5
    toc-location: left
    lightbox: true
    code-copy: true
    theme:
      light: [flatly, styles/styles.scss]
      dark:  [darkly, styles/styles.scss]
    embed-resources: false
    link-external-newwindow: true
    link-external-icon: false
    link-external-filter: '^(?:http:|https:)\/\/(?:www\.)?kader-xai\.github\.io'
    include-after-body:
      text: |
        <script src="/styles/styles.js"></script>

execute:
  warning: false
